language: python

python:
  - "3.5"
  - "3.5-dev"

install:
    - pip install -r requirements.txt
    # - pip install coveralls
    - pip install codecov

script: make test

after_success:
    - codecov --token fa9d4397-3371-4f85-a79a-0029bed5d256
    # - coveralls

branches:
  only:
  - master

notifications:
  email: false
